apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "woocommerce.fullname" . }}
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "woocommerce.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "woocommerce.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ include "woocommerce.fullname" . }}-mariadb
            - name: WORDPRESS_DB_USER
              value: {{ .Values.mariadb.auth.username }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "woocommerce.fullname" . }}-db
                  key: mariadb-password
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.mariadb.auth.database }}
            - name: WORDPRESS_USERNAME
              value: {{ .Values.wordpressUsername }}
            - name: WORDPRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "woocommerce.fullname" . }}-admin
                  key: wordpress-password
            - name: WORDPRESS_EMAIL
              value: {{ .Values.wordpressEmail }}
            - name: WORDPRESS_FIRST_NAME
              value: {{ .Values.wordpressFirstName }}
            - name: WORDPRESS_LAST_NAME
              value: {{ .Values.wordpressLastName }}
            - name: WORDPRESS_BLOG_NAME
              value: {{ .Values.wordpressBlogName }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: wordpress-data
              mountPath: /bitnami/wordpress
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: {{ include "woocommerce.fullname" . }}
