apiVersion: v1
kind: Secret
metadata:
  name: {{ include "woocommerce.fullname" . }}-db
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "woocommerce.fullname" . }}-admin
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
type: Opaque
data:
  wordpress-password: {{ .Values.wordpressPassword | b64enc | quote }}
